version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_CONFIG_FILE: /bitnami/rabbitmq/rabbitmq
    volumes:
    - ./:/bitnami/rabbitmq
  postgresql:
    container_name: postgresql
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
